name: java-webapp-gha

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main
    paths:
      - 'java-demo/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      jfrog_dns:
        description: 'your JFrog Platform SaaS URL (for example, yann.jfrog.io)'
        required: true 
        type: string
      jf_secret:
        description: 'token to configure the JFrog CLI in the Github Workflows (JF_SECRET)'
        type: string
        required: true 
      ci_secret:
        description: 'ci user s password (JF_CI_SECRET)'
        type: string
        required: true 
env:
  # JF_ENV_1: ${{ secrets.JF_SECRET }}
  JF_ENV_1: ${{ inputs.jf_secret }}
  JF_ID: jfrog-platform-training
  JF_CLI_VERSION: 2.27.1
  APP_VERSION: 2.0.0
  MVN_REPO: one-mvn
  SRC_FOLDER: java-demo/src
   
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_webapp:
    if: ${{ true }}
    runs-on: ubuntu-latest
    env:
      JFROG_BUILD_STATUS: PASS
      JAVA_VERSION: 16.0.2+7
      JAVA_DIST: zulu
      MVN_VERSION: 3.8.2
      # required by jf CLI
      # M2_HOME: /opt/hostedtoolcache/maven/3.8.2/x64 # NOT required in jf CLI v2.3.0
      MVN_REPO: one-mvn
      PROMOTE_REPO: one-mvn-release-local
    steps:
      - uses: actions/checkout@v2

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2 
        with:
          version: ${{ env.JF_CLI_VERSION }}
    
      - name: Setup Java JDK ${{ env.JAVA_DIST }} ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v2.3.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DIST }}
        
      - name: Setup Maven ${{ env.MVN_VERSION }}
        uses: stCarolas/setup-maven@v4.1
        with:
          maven-version: ${{ env.MVN_VERSION }}
    
      - name: Ping Artifactory
        run: |
            jf --version
            jf config show
            jf rt ping
            env
            
      - name: Configure JFrog CLI with Maven client
        run: | 
          jf rt mvnc \
                  --server-id-resolve=${{ env.JF_ID }} \
                  --repo-resolve-releases=${{ env.MVN_REPO }}	\
                  --repo-resolve-snapshots=${{ env.MVN_REPO }}	\
                  --server-id-deploy=${{ env.JF_ID }} \
                  --repo-deploy-releases=${{ env.MVN_REPO }} \
                  --repo-deploy-snapshots=${{ env.MVN_REPO }}

      - name: Scan dependencies
        run:  cd ${{ env.SRC_FOLDER }} && jf audit

      - name: Build webapp and scan generated artifact before upload
        run: jf mvn clean install -f ${{ env.SRC_FOLDER }}/  --no-transfer-progress
        
      - name: Publish Build Info
        run: |
          # Collect environment variables for the build
          jf rt bce 
          # Collect VCS details from git and add them to the build
          jf rt bag
          # Publish build info
          jf rt bp
          
      - name: Run test 
        run: echo running tests ...

      # - name: Promote Build 
      #   run: jf rt bpr --fail-fast=false --status "TEST_OK" --comment "promoted to the next level" ${{ env.PROMOTE_REPO }}
  
  build_docker:
    if: ${{ true }}
    needs: build_webapp
    runs-on: ubuntu-latest
    env:
      DOCKER_REG: ${{ inputs.jfrog_dns }} 
      DOCKER_REPO: one-docker
      DOCKER_USER: ci
      SRC_REPO: one-docker-dev-local
      PROMOTE_REPO: one-docker-release-local
    steps:
      - uses: actions/checkout@v2

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2  
        with:
          version: ${{ env.JF_CLI_VERSION }}

      - name: Download webapp
        run: |
          jf rt download \
            --build $JFROG_CLI_BUILD_NAME/$JFROG_CLI_BUILD_NUMBER  \
            --exclusions "*.pom;*library*" \
            --flat=true \
            --build-name=docker-$JFROG_CLI_BUILD_NAME --build-number=$JFROG_CLI_BUILD_NUMBER \
            --fail-no-op=true \
            --module=webapp \
            ${{ env.MVN_REPO }} ${{ env.SRC_FOLDER }}/multi-module-application.jar

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.DOCKER_REG }}
          username: ${{ env.DOCKER_USER }}
          password: ${{ inputs.ci_secret }}
          # password: ${{ secrets.DOCKER_SECRET }}

      - name: Build Docker image
        uses: docker/build-push-action@v2.6.1
        with:
          context: ${{ env.SRC_FOLDER }}/
          tags: ${{ env.DOCKER_REG }}/${{ env.DOCKER_REPO }}/gha-java-webapp:${{ env.APP_VERSION }}
          build-args: |
              REGISTRY=${{ env.DOCKER_REG }}
              DOCKER_REPO=punch-docker

      - name: Scan Docker image
        run: |
          jf docker scan ${{ env.DOCKER_REG }}/${{ env.DOCKER_REPO }}/gha-java-webapp:${{ env.APP_VERSION }}

      - name: Push Docker image
        run: jf docker push ${{ env.DOCKER_REG }}/${{ env.DOCKER_REPO }}/gha-java-webapp:${{ env.APP_VERSION }} --build-name=docker-$JFROG_CLI_BUILD_NAME --build-number=$JFROG_CLI_BUILD_NUMBER

      - name: Publish Docker Build Info
        run: |
          jf rt bce docker-$JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER
          jf rt bag docker-$JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER
          jf rt bp docker-$JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER
